config/routes.rb
Rails.application.routes.draw do
  # get 'note/index'
  # get 'note/show'
  # get 'note/new'
  # get 'note/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # root 'static_pages#home'

  # get '/about', to: 'static_pages#about'

  resources :notes


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord

  has_many :notes
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/note_controller.rb
class NoteController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @notes = Notes.find(params[:id])
  end

  def new
    @notes = Note.new
  end

  def create
    @notes = Note.new(notes.params)
    if @notes.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit
    @notes = Note.find(params[:id])
  end

  def update
    @notes = Note.find(params[:id])
    if @notes.update(notes_params)
      redirect_to notes_path
    else 
      render :edit
    end
  end
  
  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
  def notes_params
    params.require(:note).permit(:title, :author, :body)
  end

end

app/controllers/notes_controller.rb
class NoteController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @notes = Notes.find(params[:id])
  end

  def new
    @notes = Note.new
  end

  def create
    @notes = Note.new(notes.params)
    if @notes.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit
    @notes = Note.find(params[:id])
  end

  def update
    @notes = Note.find(params[:id])
    if @notes.update(notes_params)
      redirect_to notes_path
    else 
      render :edit
    end
  end
  
  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end

  private
  def notes_params
    params.require(:note).permit(:title, :author, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', notes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= render 'layouts/navbar' %>
<%= yield %>

  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  </body>
</html>

app/views/note/edit.html.erb
<h1>Edit Note</h1>

<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

  <%= end %>
  

app/views/note/index.html.erb
<h1>Notes</h1>

# <% @notes.each do |note| %>

#   # <%= note.title %>
#   # <%= link_to 'Show Note', note_path(note) %>
#   # <%= link_to 'Edit Note', edit_note_path(note) %>
#   # <%= link_to 'Delete Note', note, method: :delete %>
 

#   # <% end %>

#   # <%= link_to 'New Note', new_note_path %>
#   # <%= link_to 'Edit Note', edit_note_path(note) %>

<% @notes.each do |note| %>
  <%= link_to "Show Note", note_path(note) %>
  <%= link_to 'New Note', new_note_path %>
  <%= link_to 'Home', root_path %>

<% end %>

app/views/note/new.html.erb
<h1>New Note</h1>

<%= form_for @note do |f| %>
  
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

  <%= end %>

app/views/note/show.html.erb
<h1>Show Note</h1>

<%= @note.title %>
<%= @note.author %>
<%= @note.body %>

<%= link_to 'Back', notes_path %>